EWPP-53: Version field configuration should be global.
openeuropa/entity_version pull request #28
Opened 2020-07-28 15:17 UTC by sergepavle

2020-08-03 09:33 UTC, imanoleguskiza requested changes

2020-08-03 09:33 UTC, imanoleguskiza commented on README.md
> +It provides a configuration page found at "admin/config/entity-version/settings" where appropriate Version field can be selected for entities and their bundles that have at least one Version field.
Missing article: "where an appropriate Version field"

2020-08-03 09:33 UTC, imanoleguskiza commented on README.md
> +This module provides a permission called `access entity version configuration` which permits configure the version settings.
"permits configuring"

2020-08-03 12:04 UTC, 22Alexandra commented on modules/entity_version_history/src/Controller/EntityVersionHistoryController.php
> +    $history_storage = $this->entityTypeManager->getStorage('entity_version_settings');
In the checkAccess method `$history_storage` was changed to `$entity_version_storage`. We should do the same.

2020-08-03 12:04 UTC, 22Alexandra commented on tests/modules/entity_version_test/entity_version_test.info.yml
> +name: Entity Version Test
Why moving this test module? It was used only in the entity_version_history module testing the History tab, overview and other functionalities related to the entity_version_history module. I think it should stay in the submodule.

2020-08-03 12:07 UTC, imanoleguskiza submitted a review, later dismissed

2020-08-05 13:38 UTC, nagyad requested changes
Make sure you update the \entity_version_workflows_entity_presave hook to use the field from the config instead of looping through. Please make sure to mention this config in this submodule readme.

2020-08-05 13:38 UTC, nagyad commented on modules/entity_version_history/src/Controller/EntityVersionHistoryController.php
> +    $history_storage = $this->entityTypeManager->getStorage('entity_version_settings');
This was not done yet. Rename the variable.

2020-08-05 13:38 UTC, nagyad commented on README.md
> +It provides a configuration page found at "admin/config/entity-version/settings" where an appropriate Version field can be selected for entities and their bundles that have at least one Version field
Please make sure you add a line in the readme of the history tab submodule about this config is being used to read from the field for the table.

2020-08-14 15:11 UTC, brummbar requested changes

2020-08-14 15:11 UTC, brummbar commented on README.md
> +The Entity Version module attaches a version number to content entity revisions that helps content editors to understand the evolution of the content item.
Convert the empty space (now lost) into a `\` so the new line is retained.

2020-08-14 15:11 UTC, brummbar commented on entity_version.links.menu.yml
> +  description: 'Configure the entity version.'
This sounds unfinished! Maybe something like `Configure the module behaviour` (since the name is above).

2020-08-14 15:11 UTC, brummbar commented on entity_version.routing.yml
> +    _title: 'Entity Version settings'
It's either always `Version` or `version` (see above). I hate the capitalised one, let's make it lower case. `Entity version.`

2020-08-14 15:11 UTC, brummbar commented on modules/entity_version_history/README.md
> +have the history tab functionality fully operational.
This makes not clear that the field that is picked in that page will make it the one used for the history functionality. It also doesn't make clear that if you don't want to enable the functionality for a bundle, you can skip the configuration.

2020-08-14 15:11 UTC, brummbar commented on modules/entity_version_history/src/Controller/EntityVersionHistoryController.php
> +    $version_field_setting = $entity_version_storage->load($entity_type_id . '.' . $entity->bundle());
I'm a bit surprised we didn't extend the storage interface to have a method to easily retrieve this instead of creating the ID manually. Just a comment, not to change for now.

2020-08-14 15:11 UTC, brummbar commented on src/Entity/EntityVersionSettingsStorage.php
> +class EntityVersionSettingsStorage extends ConfigEntityStorage {
This class has this comment inside "Constructs a ShortcutSetStorageController object.". Let's fix it.

2020-08-14 15:11 UTC, brummbar commented on src/EntityVersionSettingsInterface.php
> +   *   Returns the EntityVersionSettings object.
Nope, it returns the called object. It could be another object that implements the interface but not a EntityVersionSettings object.

2020-08-14 15:11 UTC, brummbar commented on src/EntityVersionSettingsInterface.php
> +   *   Returns the EntityVersionSettings object.
Same as above.

2020-08-14 15:11 UTC, brummbar commented on src/EntityVersionSettingsInterface.php
> +   *   Returns the EntityVersionSettings object.
Same as above.

2020-08-14 15:11 UTC, brummbar commented on src/Entity/EntityVersionSettings.php
> + *   admin_permission = "access entity version configuration",
![image](https://user-images.githubusercontent.com/8488617/90254640-61034200-de43-11ea-9e4d-c819f04cb822.png)

2020-08-14 15:11 UTC, brummbar commented on src/Entity/EntityVersionSettings.php
> + *   admin_permission = "access entity version configuration",
We use also in our own components "administer <...>".

2020-08-14 15:11 UTC, brummbar commented on src/Form/EntityVersionSettingsForm.php
> +    $entity_version_configs = [];
This remark is about line #103. It's not true anymore that we are only interested in entities that have a canonical URL. It was true for the entity history, but not for the workflow behaviour, for example.

2020-08-14 15:11 UTC, brummbar commented on src/Form/EntityVersionSettingsForm.php
> +    $entity_version_configs = [];
Also line 108 is not entirely true. It's again valid for history only.

2020-08-14 15:11 UTC, brummbar commented on src/Form/EntityVersionSettingsForm.php
> +      '#markup' => $this->t('Configure the Entity Version field for each entity type and bundle.'),
The new description is not explicative of what this configuration is about.
`For each entity type and bundle that have at least one Entity version field, configure which field should be marked as main. Said fields will be used to apply functionalities offered by sub-modules. If no choice is made for a bundle, said functionalities will be disabled.`

2020-08-14 15:11 UTC, brummbar commented on src/Form/EntityVersionSettingsForm.php
> +      '#markup' => $this->t('Configure the Entity Version field for each entity type and bundle.'),
Given the above, remove line 156.

2020-08-14 15:11 UTC, brummbar commented on src/Form/EntityVersionSettingsForm.php
> +      '#markup' => $this->t('Configure the Entity Version field for each entity type and bundle.'),
Instead of preventing access when only one field is available, let's mark it as disabled. Like this it will more clear to the user that a choice has been made and the form is working correctly.

2020-08-14 15:11 UTC, brummbar commented on src/Form/EntityVersionSettingsForm.php
> +          '#description' => $this->t('Select the Version field.'),
```suggestion
          '#description' => $this->t('Select a main Version field for this bundle.'),
```

2020-08-14 15:11 UTC, brummbar commented on src/Form/EntityVersionSettingsForm.php
> +    $this->messenger->addStatus($this->t('The Entity Version configuration has been saved.'));
```suggestion
    $this->messenger->addStatus($this->t('The Entity version configuration has been saved.'));
```
Let's not use camel case for names.

2020-08-14 15:11 UTC, brummbar commented on config/schema/entity_version.schema.yml
> +  label: 'Entity Version Settings'
Let's kill the camel case.

2020-08-14 15:11 UTC, brummbar commented on README.md
> +It provides a configuration page found at "admin/config/entity-version/settings" where an appropriate Version field can be selected for entities and their bundles that have at least one Version field
Add that then this field will be used as target for functionalities provided by sub-modules.

2020-08-14 15:11 UTC, brummbar commented on entity_version.install
> + * Install and update functions for the Entity Version module.
No camel.

2020-08-14 15:11 UTC, brummbar commented on modules/entity_version_workflows/README.md
> +have the entity version workflows functionality fully operational.
Let's add also here that if no field is configured, the workflow functionality is not applied.

2020-08-18 15:06 UTC, brummbar requested changes

2020-08-18 15:06 UTC, brummbar commented on src/Form/EntityVersionSettingsForm.php
> -      if (!$definition->isRevisionable()) {
Now we removed this but we didn't put this check anywhere. I created a non-revisionable content entity, marked the field as main and got a critical exception when visiting the path. We also need to add tests that the history tab is not generated for entities without canonical and entities not revisionable.

2020-08-18 15:06 UTC, brummbar commented on config/schema/entity_version.schema.yml
> +      label: 'Entity Type ID'
```suggestion
      label: 'Entity type ID'
```

2020-08-18 15:06 UTC, brummbar commented on entity_version.permissions.yml
> +  title: 'Access the entity version configuration'
```suggestion
administer entity version:
  title: 'Administer the entity version module'
```

2020-08-18 15:06 UTC, brummbar commented on tests/src/FunctionalJavascript/EntityVersionSettingsTest.php
>      // Check that there is only one select field and it's not visible.
This comment needs to be updated.

2020-08-18 15:06 UTC, brummbar commented on tests/src/FunctionalJavascript/EntityVersionSettingsTest.php
> +    $this->assertEquals('entity_test_rev_entity_test_rev', $select->getAttribute('name'));
What are we testing here? I cannot understand 😓

2020-08-19 09:57 UTC, sergepavle commented on tests/src/FunctionalJavascript/EntityVersionSettingsTest.php
> +    $this->assertEquals('entity_test_rev_entity_test_rev', $select->getAttribute('name'));
It is leftover from previous logic when we asserting that have available only selectboxes for the target field with more than 1 option.
I have fixed that.

2020-08-20 13:28 UTC, brummbar approved these changes

2020-08-21 12:32 UTC, nagyad approved these changes

2020-08-21 12:32 UTC, merged