EWPP-1912: Update to PHP8 and Composer v2.
openeuropa/entity_version pull request #48
Opened 2022-02-02 13:06 UTC by 22Alexandra

2022-02-04 14:31 UTC, nagyad approved these changes, later dismissed

2022-02-04 15:49 UTC, sergepavle requested changes

2022-02-04 15:49 UTC, sergepavle commented on .drone.yml
>        # @link https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
Let's remove the deprecated comment.

2022-02-04 15:49 UTC, sergepavle commented on composer.json
> +    ],
We have to move _readme inside `extra` property
```See https://getcomposer.org/doc/04-schema.md for details on the schema
# Publish errors
- The property _readme is not defined and the definition does not allow additional properties
```

2022-02-04 15:49 UTC, sergepavle commented on composer.json
>      "minimum-stability": "dev",
```
# General warnings
- License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0-or-later" instead
```

2022-02-07 08:57 UTC, sergepavle approved these changes

2022-02-07 09:55 UTC, nagyad approved these changes

2022-02-07 14:47 UTC, merged