EWPP-2990: Drupal 10 compatibility.
openeuropa/entity_version pull request #55
Opened 2023-02-10 21:08 UTC by brummbar

2023-02-17 10:01 UTC, drishu requested changes
The rest of it looks good

2023-02-17 10:01 UTC, drishu commented on .drone.yml
> +      - composer require drupal/core:^${CORE_VERSION} drupal/core-composer-scaffold:^${CORE_VERSION} drupal/core-dev:^${CORE_VERSION} --update-with-all-dependencies --ansi --no-progress --no-interact
```suggestion
      - composer require drupal/core:~${CORE_VERSION} drupal/core-composer-scaffold:~${CORE_VERSION} drupal/core-dev:^${CORE_VERSION} --update-with-all-dependencies --ansi --no-progress --no-interaction
```

2023-02-17 10:01 UTC, drishu commented on .drone.yml
> +    - CORE_VERSION: 9.4
```suggestion
    - CORE_VERSION: 9.4.0
```

2023-02-17 10:01 UTC, drishu commented on .drone.yml
> +    - CORE_VERSION: 9.4
```suggestion
    - CORE_VERSION: 9.4.0
```

2023-02-17 14:39 UTC, drishu approved these changes

2023-02-22 08:35 UTC, 22Alexandra commented on .drone.yml
> +    - CORE_VERSION: 9.4
Why tho? Patch versions usually include security updates and maybe we should test using the latest patch instead of `.0`.

2023-02-22 08:42 UTC, 22Alexandra commented on .drone.yml
> +    - CORE_VERSION: 9.4
Nvm.

2023-02-22 08:43 UTC, 22Alexandra approved these changes

2023-02-22 15:31 UTC, merged