EWPP-3974: Update test matrix and supported core version.
openeuropa/entity_version pull request #58
Opened 2024-02-05 19:36 UTC by brummbar

2024-02-06 08:50 UTC, nagyad submitted a review, later dismissed

2024-02-06 16:32 UTC, AaronGilMartinez requested changes

2024-02-06 16:32 UTC, AaronGilMartinez commented on composer.json
>          "php": ">=8.0",
I think we can require 8.1 as minimum here

2024-02-06 16:36 UTC, AaronGilMartinez approved these changes

2024-02-07 10:04 UTC, nagyad approved these changes

2024-02-07 10:09 UTC, merged